version: '3.8'
services:

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

    networks:
      - app-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"       # Internal communication or within Docker network
      - "29092:29092"     # External access from host
    environment:
      KAFKA_HOST: 'kafka'
      KAFKA_PORT: '9092'
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'  # Enable automatic topic creation
      KAFKA_CREATE_TOPICS: "transactions_topic:1:1"  # TopicName:Partitions:ReplicationFactor

      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
#    volumes:
#      - kafka-data:/bitnami/kafka
    networks:
      - app-network
    restart: on-failure

  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=CassandraCluster
      - CASSANDRA_LISTEN_ADDRESS=cassandra
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra

#    volumes:
#      - cassandra-data:/var/lib/cassandra
#      - ./cassandra.yaml:/opt/bitnami/cassandra/conf/cassandra.yaml
    networks:
      - app-network


  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
#      - spark-network
      - app-network
    volumes:
      - ./spark_scripts:/opt/bitnami/spark/scripts  # Mounting the local spark_scripts directory
      - ./data:/opt/spark-data

    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master


  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark-master

    networks:
      - app-network

    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077


  spark-job:
    image: bitnami/spark:latest
    container_name: spark-job
    networks:
      - app-network
    environment:
      SPARK_MASTER_URL: spark://spark-master:7077
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
    depends_on:
      - spark-master
      - kafka
      - cassandra
    volumes:
      - ./spark_scripts:/opt/bitnami/spark/scripts

#    command: /opt/bitnami/spark/bin/spark-submit --master spark://spark-master:7077 /opt/bitnami/spark/scripts/pi.py
    command: /opt/bitnami/spark/bin/spark-submit --packages org.apache.spark:spark-streaming-kafka-0-10_2.12:3.5.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1 --master spark://spark-master:7077 /opt/bitnami/spark/scripts/test_3.py
#    restart: on-failure


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - cassandra
    environment:
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
      WAIT_HOSTS: cassandra:9042

networks:
  app-network:
    driver: bridge

volumes:
  kafka-data:
  cassandra-data:
